### ISSUE TITLE
Text-ui-test problem in reading next line of command from input file

### ISSUE THREAD

**Issue by HongJiancheng** [nus-tic4001-AY2021S1/forum#1]
In setting up text-ui-test, the script could only read the first line of command from input file, and not able to read subsequent lines of commands. Thus, output is always shown only the result of executing first line of command.

Could anyone kindly suggest any way to resolve this issue?

Thanks.

**Comment by tototto** [comment]
I also encountered the same issue. 

Only the first line of input from input.txt was read. On top of that there was an exception thrown for Scanner.nextLine. May i confirm that this error was thrown due to the 2nd line onwards not being fed to Duke?

However input.txt actually contains:

**todo read book
deadline return book /by 12/12/12 6pm**

The full execution results are as per below:

(base) Jun-Wen-MacBook-Pro:text-ui-test tayjunwen$ /bin/bash /Users/tayjunwen/Desktop/TIC4001_Software_Engineering_Practicum/ip/text-ui-test/test.sh
Note: ../src/main/java/listHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at inputHandler.getUserInput(inputHandler.java:7)
        at Duke.main(Duke.java:19)
11,15d10
< ----------------------------------------
<  Got it. I've added this task: 
<    [T][?] read book
<  Now you have 1 tasks in the list.
< ----------------------------------------
Test result: FAILED
(base) Jun-Wen-MacBook-Pro:text-ui-test tayjunwen$

**Comment by damithc** [comment]
![image](https://user-images.githubusercontent.com/1673303/90974307-92bf8b80-e55c-11ea-9bf7-60310bc4596a.png)

This approach results in a new Scanner object is being created for each user input. Normally, this is OK but when feeding the input from a file, the first Scanner object swallows all the lines from the input file (but processes only the first line). Subsequent Scanner objects have nothing to read.

Solution: create the Scanner object once and put that into a static variable.  Then, use the same object every time.


```java
import java.util.Scanner;

public class inputHandler {

    private static Scanner s  = new Scanner(System.in);

    public String getUserInput(){
        String command = s.nextLine();
        return command;
    }
}
```

**Comment by HongJiancheng** [comment]
> ![image](https://user-images.githubusercontent.com/1673303/90974307-92bf8b80-e55c-11ea-9bf7-60310bc4596a.png)
> 
> This approach results in a new Scanner object is being created for each user input. Normally, this is OK but when feeding the input from a file, the first Scanner object swallows all the lines from the input file (but processes only the first line). Subsequent Scanner objects have nothing to read.
> 
> Solution: create the Scanner object once and put that into a static variable. Then, use the same object every time.
> 
> ```java
> import java.util.Scanner;
> 
> public class inputHandler {
> 
>     private static Scanner s  = new Scanner(System.in);
> 
>     public String getUserInput(){
>         String command = s.nextLine();
>         return command;
>     }
> }
> ```

Noted with many thanks!
